version: '2'
services:
    asart-app:
        image: asart
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://asart-mysql:3306/asart?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    asart-mysql:
        extends:
            file: mysql.yml
            service: asart-mysql
